### ISSUE TITLE
百度文库的广告解决。

### ISSUE THREAD

**Issue by needhourger** [HelloCodeMing/baidu-wenku#9]
右下角广告已经移除
但是在针对上百页的文档的时候可能现有代码依旧无法下拉到最底部，希望大佬改进吧···

**Comment by hellocodeM** [comment]
我已经忘了JavaScript怎么写了

**Comment by needhourger** [comment]
hhh
这个方法不能下载pdf格式的文档，唯一的局限了~

**Comment by hellocodeM** [comment]
可能在大学毕业之后就没怎么用过百度文库了，

**Comment by needhourger** [comment]
我也是有个项目需求，不然基本不用百度文库
